# Generated by Django 3.1.7 on 2021-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210312_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
