# Generated by Django 3.1.7 on 2021-03-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210312_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
