# Generated by Django 3.1.7 on 2021-03-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210312_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='test_id',
            new_name='q_id',
        ),
    ]
