# Generated by Django 3.1.7 on 2021-03-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='ques',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
